import React, { useState } from 'react';
import { Sparkles, History } from 'lucide-react';
import { WordCounter } from './WordCounter';
import { ModelSelector } from '../shared/ModelSelector';
import { useApplicationStore } from '@/stores/applicationStore';
import { useAIStore } from '@/stores/aiStore';
import { contentGenerator } from '@/services/generator/contentGenerator';
import { Button } from '../ui/Button';

interface QuestionEditorProps {
  questionId: string;
}

export const QuestionEditor: React.FC<QuestionEditorProps> = ({
  questionId,
}) => {
  const { application, updateQuestionContent } = useApplicationStore();
  const { isGenerating, currentTask } = useAIStore();
  const [error, setError] = useState<string | null>(null);

  const question = application?.questions.find((q) => q.id === questionId);
  const currentVersion = question?.versions.find(
    (v) => v.id === question.currentVersionId
  );

  if (!question || !currentVersion) {
    return (
      <div className="h-full flex items-center justify-center text-text-muted">
        No question selected
      </div>
    );
  }

  const handleGenerate = async () => {
    setError(null);
    try {
      await contentGenerator.generate(questionId, 'editor-pane');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Generation failed');
    }
  };

  return (
    <div className="h-full flex flex-col">
      {/* Toolbar */}
      <div className="px-4 py-2 bg-bg-secondary border-b border-border-muted flex items-center justify-between">
        <div className="flex items-center gap-4">
          <span className="text-sm font-semibold text-text-primary">
            {question.title}
          </span>
          {/* Model Selection for this pane */}
          <ModelSelector contextId="editor-pane" />
        </div>

        <div className="flex items-center gap-3">
          <WordCounter
            current={currentVersion.wordCount}
            max={question.maxWords}
          />
          <div className="h-4 w-px bg-border-muted" />
          <Button
            variant="ghost"
            size="sm"
            onClick={handleGenerate}
            disabled={isGenerating}
            className="text-accent-purple hover:text-accent-purple"
          >
            <Sparkles className="w-4 h-4 mr-1.5" />
            {isGenerating ? 'Generating...' : 'Generate Answer'}
          </Button>
          {question.versions.length > 1 && (
            <Button
              variant="ghost"
              size="sm"
              className="text-text-muted hover:text-text-primary"
            >
              <History className="w-4 h-4 mr-1.5" />
              Versions ({question.versions.length})
            </Button>
          )}
        </div>
      </div>

      {/* Question Prompt */}
      {question.promptText && (
        <div className="px-6 py-3 bg-bg-elevated border-b border-border-muted">
          <p className="text-sm text-text-secondary italic">
            {question.promptText}
          </p>
        </div>
      )}

      {/* Error Display */}
      {error && (
        <div className="px-6 py-3 bg-accent-red/10 border-b border-accent-red/20">
          <p className="text-sm text-accent-red">{error}</p>
        </div>
      )}

      {/* Loading State */}
      {isGenerating && (
        <div className="px-6 py-3 bg-accent-purple/10 border-b border-accent-purple/20">
          <p className="text-sm text-accent-purple">{currentTask}</p>
        </div>
      )}

      {/* Main Text Area - Simplified, no inline widgets */}
      <div className="flex-1 p-6 overflow-auto">
        <textarea
          className="w-full h-full bg-transparent border-none outline-none resize-none text-base leading-relaxed text-text-primary placeholder-text-muted font-sans"
          value={currentVersion.content}
          onChange={(e) => updateQuestionContent(questionId, e.target.value)}
          placeholder="Start writing or select a model to generate content..."
          spellCheck={true}
          disabled={isGenerating}
        />
      </div>

      {/* Footer Info */}
      <div className="px-6 py-2 bg-bg-secondary border-t border-border-muted flex items-center justify-between text-xs text-text-muted">
        <span>
          {currentVersion.source === 'ai'
            ? `Generated by ${currentVersion.generatedByModelId || 'AI'}`
            : 'Manual entry'}
        </span>
        <span>
          Last updated: {new Date(currentVersion.createdAt).toLocaleString()}
        </span>
      </div>
    </div>
  );
};
